version: "3"
services:
  mongodb:
    image: mongo:latest
    logging:
      driver: "journald"
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - /data/mongodb:/data/db:rw
      - /opt/mongodb/config/mongod.conf:/etc/mongod.conf
      - /opt/mongodb/rsInit.js:/tmp/rsInit.js
      - /opt/mongodb/ssl:/etc/ssl
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip",
        "0.0.0.0",
        "--replSet",
        "rs0",
        "--auth",
        "--sslMode",
        "requireSSL",
        "--sslPEMKeyFile",
        "/etc/ssl/mongo.pem",
        "--keyFile",
        "/etc/ssl/keyfile",
        "--sslAllowConnectionsWithoutCertificates",
      ]
    networks:
      - mongodb

networks:
  mongodb:
    driver: bridge
